skills = [
    "Athletics",
    "Acrobatics",
    "Sleight of Hand",
    "Stealth",
    "Arcana",
    "History",
    "Investigation",
    "Nature",
    "Religion",
    "Animal Handling",
    "Insight",
    "Medicine",
    "Perception",
    "Survival",
    "Deception",
    "Intimidation",
    "Performance",
    "Persuasion",
]

instruments = [ 
    "Bagpipes",
    "Drum",
    "Dulcimer",
    "Flute",
    "Horn",
    "Lute",
    "Lyre",
    "Pan flute",
    "Shawm",
    "Viol",
]

wizard_cantrips = [
    "Acid Splash",
    "Blade Ward"
    "Booming Blade",
    "Chill Touch",
    "Control Flames",
    "Create Bonfire",
    "Dancing Lights",
    "Encode Thoughts",
    "Fire Bolt",
    "Friends",
    "Frostbite",
    "Green-Flame Blade",
    "Gust",
    "Infestation",
    "Light",
    "Lightning Lure",
    "Mage Hand",
    "Mending",
    "Message",
    "Mind Sliver",
    "Minor Illusion",
    "Mold Earth",
    "On/Off (UA)",
    "Poison Spray",
    "Prestidigitation",
    "Ray of Frost",
    "Sapping Sting",
    "Shape Water",
    "Shocking Grasp",
    "Sword Burst",
    "Thunderclap",
    "Toll the Dead",
    "True Strike"
]

bard_cantrips = [
    "Blade Ward",
    "Dancing Lights",
    "Friends",
    "Light",
    "Mage Hand",
    "Mending",
    "Message",
    "Minor Illusion",
    "Prestidigitation",
    "Thunderclap",
    "True Strike",
    "Vicious Mockery",
]

bard_spells = [
    "Animal Friendship",
    "Bane",
    "Charm Person",
    "Color Spray",
    "Command",
    "Comprehend Languages",
    "Cure Wounds",
    "Detect Magic",
    "Disguise Self",
    "Dissonant Whispers",
    "Distort Value",
    "Earth Tremor",
    "Faerie Fire",
    "Feather Fall",
    "Guiding Hand (UA)",
    "Healing Word",
    "Heroism",
    "Identify",
    "Illusory Script",
    "Longstrider",
    "Puppet (UA)",
    "Sense Emotion (UA)",
    "Silent Image",
    "Silvery Barbs",
    "Sleep",
    "Speak with Animals",
    "Sudden Awakening (UA)",
    "Tasha's Hideous Laughter",
    "Thunderwave",
    "Unearthly Chorus (UA)",
    "Unseen Servant",
]

cleric_cantrips = [
    "Guidance",
    "Hand of Radiance (UA)",
    "Light",
    "Mending",
    "Resistance",
    "Sacred Flame",
    "Spare the Dying",
    "Thaumaturgy",
    "Toll the Dead",
    "Virtue (UA)",
    "Word of Radiance"
]

druid_cantrips = [
    "Control Flames",
    "Create Bonfire",
    "Druidcraft",
    "Frostbite",
    "Guidance",
    "Gust",
    "Infestation",
    "Magic Stone",
    "Mending",
    "Mold Earth",
    "Poison Spray",
    "Primal Savagery",
    "Produce Flame",
    "Resistance",
    "Shape Water",
    "Shillelagh",
    "Thorn Whip",
    "Thunderclap"
]

sorcerer_cantrips = [
    "Acid Splash",
    "Blade Ward",
    "Booming Blade",
    "Chill Touch",
    "Control Flames",
    "Create Bonfire",
    "Dancing Lights",
    "Fire Bolt",
    "Friends",
    "Frostbite",
    "Green-Flame Blade",
    "Gust",
    "Infestation",
    "Light",
    "Lightning Lure",
    "Mage Hand",
    "Mending",
    "Message",
    "Mind Sliver",
    "Minor Illusion",
    "Mold Earth",
    "On/Off (UA)",
    "Poison Spray",
    "Prestidigitation",
    "Ray of Frost",
    "Shape Water",
    "Shocking Grasp",
    "Sword Burst",
    "Thunderclap",
    "True Strike"
]

sorcerer_spells = [
    "Absorb Elements",
    "Acid Stream (UA)",
    "Burning Hands",
    "Catapult",
    "Chaos Bolt",
    "Charm Person",
    "Chromatic Orb",
    "Color Spray",
    "Comprehend Languages",
    "Detect Magic",
    "Disguise Self",
    "Distort Value",
    "Earth Tremor",
    "Expeditious Retreat",
    "False Life",
    "Feather Fall",
    "Fog Cloud",
    "Grease",
    "Ice Knife",
    "Id Insinuation (UA)",
    "Infallible Relay (UA)",
    "Jump",
    "Mage Armor",
    "Magic Missile",
    "Ray of Sickness",
    "Remote Access (UA)",
    "Shield",
    "Silent Image",
    "Silvery Barbs",
    "Sleep",
    "Sudden Awakening (UA)",
    "Tasha's Caustic Brew",
    "Thunderwave",
    "Witch Bolt"
]

warlock_cantrips = [
    "Blade Ward",
    "Booming Blade",
    "Chill Touch",
    "Create Bonfire",
    "Eldritch Blast",
    "Friends",
    "Frostbite",
    "Green-Flame Blade",
    "Infestation",
    "Lightning Lure",
    "Mage Hand",
    "Magic Stone",
    "Mind Sliver",
    "Minor Illusion",
    "On/Off (UA)",
    "Poison Spray",
    "Prestidigitation",
    "Sword Burst",
    "Thunderclap",
    "Toll the Dead",
    "True Strike",
]

warlock_spells = [
    "Armor of Agathys",
    "Arms of Hadar",
    "Cause Fear",
    "Charm Person",
    "Comprehend Languages",
    "Distort Value",
    "Expeditious Retreat",
    "Healing Elixir (UA)",
    "Hellish Rebuke",
    "Hex",
    "Id Insinuation (UA)",
    "Illusory Script",
    "Infallible Relay (UA)",
    "Protection from Evil and Good",
    "Puppet (UA)",
    "Remote Access (UA)",
    "Sense Emotion (UA)",
    "Unseen Servant",
    "Witch Bolt",
]

wizard_spells = [
    "Absorb Elements",
    "Acid Stream (UA)",
    "Alarm",
    "Burning Hands",
    "Catapult",
    "Cause Fear",
    "Charm Person",
    "Chromatic Orb",
    "Color Spray",
    "Comprehend Languages",
    "Detect Magic",
    "Disguise Self",
    "Distort Value",
    "Earth Tremor",
    "Expeditious Retreat",
    "False Life",
    "Feather Fall",
    "Find Familiar",
    "Fog Cloud",
    "Frost Fingers",
    "Gift of Alacrity",
    "Grease 	Conjuration",
    "Guiding Hand (UA)",
    "Healing Elixir (UA)",
    "Ice Knife",
    "Id Insinuation (UA)",
    "Identify",
    "Illusory Script",
    "Infallible Relay (UA)",
    "Jim's Magic Missile",
    "Jump",
    "Longstrider",
    "Mage Armor",
    "Magic Missile",
    "Magnify Gravity",
    "Protection from Evil and Good",
    "Puppet (UA)",
    "Ray of Sickness",
    "Remote Access (UA)",
    "Sense Emotion (UA)",
    "Shield",
    "Silent Image",
    "Silvery Barbs",
    "Sleep",
    "Snare",
    "Sudden Awakening (UA)",
    "Tasha's Caustic Brew",
    "Tasha's Hideous Laughter",
    "Tenser's Floating Disk",
    "Thunderwave",
    "Unseen Servant",
    "Witch Bolt",
]

ASSETS = {
    "skills": skills,
    "instruments": instruments,
    "wizard_cantrips": wizard_cantrips,
    "bard_spells": bard_spells,
    "bard_cantrips": bard_cantrips,
    "cleric_cantrips": cleric_cantrips,
    "druid_cantrips": druid_cantrips,
    "sorcerer_cantrips": sorcerer_cantrips,
    "sorcerer_spells": sorcerer_spells,
    "warlock_cantrips": warlock_cantrips,
    "warlock_spells": warlock_spells,
    "wizard_spells": wizard_spells
}

def get_asset(asset_type: str):
    return ASSETS.get(asset_type)