skills = [
    "Athletics",
    "Acrobatics",
    "Sleight of Hand",
    "Stealth",
    "Arcana",
    "History",
    "Investigation",
    "Nature",
    "Religion",
    "Animal Handling",
    "Insight",
    "Medicine",
    "Perception",
    "Survival",
    "Deception",
    "Intimidation",
    "Performance",
    "Persuasion",
]

instruments = [ 
    "Bagpipes",
    "Drum",
    "Dulcimer",
    "Flute",
    "Horn",
    "Lute",
    "Lyre",
    "Pan flute",
    "Shawm",
    "Viol",
]

wizard_cantrips = [
    "Acid Splash",
    "Blade Ward"
    "Booming Blade",
    "Chill Touch",
    "Control Flames",
    "Create Bonfire",
    "Dancing Lights",
    "Encode Thoughts",
    "Fire Bolt",
    "Friends",
    "Frostbite",
    "Green-Flame Blade",
    "Gust",
    "Infestation",
    "Light",
    "Lightning Lure",
    "Mage Hand",
    "Mending",
    "Message",
    "Mind Sliver",
    "Minor Illusion",
    "Mold Earth",
    "On/Off (UA)",
    "Poison Spray",
    "Prestidigitation",
    "Ray of Frost",
    "Sapping Sting",
    "Shape Water",
    "Shocking Grasp",
    "Sword Burst",
    "Thunderclap",
    "Toll the Dead",
    "True Strike"
]

bard_cantrips = [
    "Blade Ward",
    "Dancing Lights",
    "Friends",
    "Light",
    "Mage Hand",
    "Mending",
    "Message",
    "Minor Illusion",
    "Prestidigitation",
    "Thunderclap",
    "True Strike",
    "Vicious Mockery",
]

bard_spells = [
    "Animal Friendship",
    "Bane",
    "Charm Person",
    "Color Spray",
    "Command",
    "Comprehend Languages",
    "Cure Wounds",
    "Detect Magic",
    "Disguise Self",
    "Dissonant Whispers",
    "Distort Value",
    "Earth Tremor",
    "Faerie Fire",
    "Feather Fall",
    "Guiding Hand (UA)",
    "Healing Word",
    "Heroism",
    "Identify",
    "Illusory Script",
    "Longstrider",
    "Puppet (UA)",
    "Sense Emotion (UA)",
    "Silent Image",
    "Silvery Barbs",
    "Sleep",
    "Speak with Animals",
    "Sudden Awakening (UA)",
    "Tasha's Hideous Laughter",
    "Thunderwave",
    "Unearthly Chorus (UA)",
    "Unseen Servant",
]

ASSETS = {
    "skills": skills,
    "instruments": instruments,
    "wizard_cantrips": wizard_cantrips,
    "bard_spells": bard_spells,
    "bard_cantrips": bard_cantrips
}

def get_asset(asset_type: str):
    return ASSETS.get(asset_type)